### ISSUE TITLE
horizontal connectGrobs don't always connect to the edge of the boxGrob

### ISSUE THREAD

**Issue by ghost** [aghaynes/misc#1]
Hi,

I was running the example [here](https://aghaynes.wordpress.com/2018/05/09/flow-charts-in-r/), and noticed that the horizontal arrow connecting the Total to the Ineligible boxGrobs doesn't always touch the left-edge of the the Ineligible boxGrob.

It seems to depend on the width of the viewing window in RStudio. This does not seem to be the case for the vertical arrow, which always seem to perfectly connect to the top of the correct boxGrob.

Is there a way to force the arrow to touch the side of the box and not go any further?

**Narrow plotting window:**
![image](https://user-images.githubusercontent.com/48337093/65558753-574ac480-df7b-11e9-9fe6-8ccd0cca5320.png)

**Wide plotting window:**
![image](https://user-images.githubusercontent.com/48337093/65558799-6d588500-df7b-11e9-8ee1-0e6993a187ee.png)

**Comment by ghost** [comment]
I can get around it by fixing the width of the ineligible box: 
inel <- boxGrob("Ineligible\n N = NNN", x=rightx, y=.825, box_gp = gp, width = unit(2, "inch"), height = .05)

Not quite sure why this works

**Comment by aghaynes** [comment]
Glad to know that you found a solution...
I'm not sure why this happens... could be something to do with resizing the RStudio pane... I'm aware of a a few things that behave strangely with that...
I recommend to work with whichever device you ultimately want (png or jpeg or whatever), then you can fix the dimensions and go from there...
